
export default {
    "cosmos:rocket_tier_1_item": [
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:rocket_fins",
        "cosmos:rocket_fins",
        "cosmos:rocket_fins",
        "cosmos:rocket_fins",
        "cosmos:rocket_engine",
        "cosmos:nose_cone",
    ], //14 items
    "cosmos:rocket_tier_2_item": [
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:tier_1_booster",
        "cosmos:rocket_fins",
        "cosmos:rocket_fins",
        "cosmos:tier_1_booster",
        "cosmos:rocket_fins",
        "cosmos:rocket_fins",
        "cosmos:rocket_engine",
        "cosmos:nose_cone",
    ], //18 items
    "cosmos:rocket_tier_3_item": [
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:heavy_duty_plate_tier3",
        "cosmos:tier_1_booster",
        "cosmos:heavy_rocket_fins",
        "cosmos:heavy_rocket_fins",
        "cosmos:tier_1_booster",
        "cosmos:heavy_rocket_fins",
        "cosmos:heavy_rocket_fins",
        "cosmos:heavy_rocket_engine",
        "cosmos:heavy_nose_cone",
    ], //18 items
    "cosmos:moon_buggy_item": [
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:buggy_seat",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:heavy_duty_plate",
        "cosmos:buggy_wheel",
        "cosmos:buggy_wheel",
        "cosmos:buggy_wheel",
        "cosmos:buggy_wheel",
    ], //14 items
    "cosmos:cargo_rocket_item": [
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:heavy_duty_plate_tier2",
        "cosmos:rocket_fins",
        "cosmos:rocket_fins",
        "cosmos:rocket_fins",
        "cosmos:rocket_fins",
        "cosmos:rocket_engine",
        "cosmos:advanced_wafer",
        "cosmos:nose_cone",
    ], //13 items
    "cosmos:astro_miner_item": [
        "cosmos:heavy_duty_plate",
        "cosmos:orion_drive",
        "cosmos:heavy_duty_plate",
        "cosmos:orion_drive",

        "cosmos:heavy_duty_plate",
        "cosmos:advanced_wafer",
        "minecraft:chest",
        "minecraft:chest",
        "cosmos:orion_drive",

        "cosmos:orion_drive",
        "cosmos:heavy_duty_plate",
        "cosmos:orion_drive",

        "cosmos:beam_core",
        "cosmos:steel_pole",
    ] //14 items
}
